# Generated by Django 5.2.2 on 2025-06-06 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        default="tool_images/default.jpg", upload_to="tool_images/"
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[("available", "Available"), ("borrowed", "Borrowed")],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("pickup_address", models.CharField(max_length=255)),
                ("posted_time", models.DateTimeField(auto_now_add=True)),
                (
                    "preferred_pickup_time",
                    models.CharField(
                        help_text="e.g., Weekdays after 5 PM", max_length=100
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
